=== dobrivoje/Algorithms/src/main/resources/xml/schemes/fileStructure.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="FileStruct">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Dir">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element type="xs:string" name="File" maxOccurs="unbounded" minOccurs="0"/>
                            <xs:element name="Dir" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="File" maxOccurs="unbounded" minOccurs="0"/>
                                        <xs:element name="Dir" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="File" maxOccurs="unbounded" minOccurs="0"/>
                                                    <xs:element name="Dir" maxOccurs="unbounded" minOccurs="0">
                                                        <xs:complexType mixed="true">
                                                            <xs:sequence>
                                                                <xs:element name="Dir" maxOccurs="unbounded" minOccurs="0">
                                                                    <xs:complexType mixed="true">
                                                                        <xs:sequence>
                                                                            <xs:element name="Dir" minOccurs="0">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element type="xs:string" name="File" maxOccurs="unbounded" minOccurs="0"/>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute type="xs:string" name="name"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute type="xs:string" name="name" use="optional"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute type="xs:string" name="name" use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="name"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dobrivoje/Algorithms/src/main/resources/xml/fileStruct.xml
<?xml version="1.0" encoding="UTF-8"?>

<FileStruct xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='schemes/fileStructure.xsd'>
    <Dir name="C:\">
        <File>hiber.sys</File>
        <Dir name="Windows" />
        <Dir name="Users">
            <File>sysFile1</File>
            <File>sysFile2</File>
            <Dir name="root">
                <File>Neki fajl1</File>
                <File>Neki fajl2</File>
                <File>Neki fajl3</File>
                <Dir name="d1"></Dir>
                <Dir name="d2"></Dir>
                <Dir name="d3">
                    <Dir name="subDir1"></Dir>
                    <Dir name="subDir2">
                        <Dir name="subSubDir1">
                            <File>name1</File>
                            <File>name2</File>
                        </Dir>
                    </Dir>
                    <Dir name="subDir3"></Dir>
                </Dir>
                        
            </Dir>
        </Dir>
    </Dir>
</FileStruct>
