=== dobrivoje/Algorithms/src/main/resources/xml/schemes/semaKnjige.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="BookCatalogue">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:float" name="Author"/>
                            <xs:element name="Cost" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:attribute type="xs:string" name="cenovnik" use="required"/>
                                    <xs:sequence>
                                        <xs:element type="xs:short" name="MPCena" minOccurs="0"/>
                                        <xs:element type="xs:short" name="VPCena" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="Date"/>
                            <xs:element type="xs:string" name="ISBN"/>
                            <xs:element type="xs:string" name="Publisher"/>
                            <xs:element type="xs:string" name="Title"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dobrivoje/Algorithms/src/main/resources/xml/knjiga.xml
<?xml version="1.0" encoding="UTF-8"?>

<BookCatalogue xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='schemes/semaKnjige.xsd'>
    <Book>
        <Author>Dobrivoje</Author>
        <Cost cenovnik="true">
            <VPCena>1000</VPCena>
            <MPCena>1200</MPCena>
        </Cost>
        <Title>Moja knjiga</Title>
    </Book>
    <Book>
        <Author>neki autor</Author>
        <Cost vpCena="true">
            <VPCena>1200</VPCena>
        </Cost>
        <Cost cenovnik="true">
            <MPCena>1200</MPCena>
        </Cost>
    </Book>
</BookCatalogue>
